### PR TITLE
fix: Setting avatar src correctly resets error state

### LINKED ISSUE #138: Avatar's hasError state is not reset when src is changed
## Description  
Avatar's hasError state is not reset when src is changed.

## Steps to reproduce  

1. Open the avatar story.
2. Enter invalid url for src.
3. Enter valid url for src.

## Result  
The valid url is not loaded.

## Expected result  
The valid url should be loaded.

### PR DESCRIPTION
**Pull request by rkaraivanov**
Closes #138

### CODE REVIEW

File: src/components/avatar/avatar.ts [hunk 1]
```diff
@@ -25,9 +25,18 @@ export default class IgcAvatarComponent extends SizableMixin(LitElement) {
   /** @private */
   public static styles = [styles];
 
+  public set src(val: string) {
```
Comment (DiyanDimitrov) [inline src/components/avatar/avatar.ts:28]: What do you think about using the `watch` decorator instead custom get/set?

Comment (rkaraivanov) [reply src/components/avatar/avatar.ts:28]: Yes, but then I would have to create a separate method for resetting the error state and decorate it.
This method will not be called anywhere so I would have to make the linter to ignore it, as it is an error otherwise.
I think this a bit clearer in this scenario.

Comment (DiyanDimitrov) [reply src/components/avatar/avatar.ts:28]: If the method is protected the linter would be fine with it. Personally I think a custom get/set looks more complicated and is error-prone since you may forgot to call `requestUpdate`.

**Review by DiyanDimitrov — APPROVED** [review]
