### PR TITLE
fix(range-slider): add ariaValueText

### LINKED ISSUE #477: Range slider accessibility improvements
## Description  
The screen reader does not tell you on which thumb you are it only reads the value of the thumb.

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #477

### CODE REVIEW

File: src/components/slider/slider-base.ts [hunk 1]
```diff
@@ -544,8 +544,37 @@ export class IgcSliderBaseComponent extends LitElement {
...
+
+    const thumbs = this.shadowRoot?.querySelectorAll('div[part="thumb"]');
+    thumbs?.forEach((t) => {
+      if (t.id !== thumbId) {
+        this.activeThumb?.setAttribute(
+          'aria-valuetext',
+          `${Math.min(
+            parseInt(thumbVal!),
+            parseInt(t.ariaValueNow!)
+          )} - ${Math.max(parseInt(thumbVal!), parseInt(t.ariaValueNow!))}`
```
Comment (rkaraivanov) [inline src/components/slider/slider-base.ts:560]: Since step can be decimal, maybe parse to float and format it to step precision.
This should account for the **discrete** property as well, since when active the value is unbound from the step property.

File: src/components/slider/slider-base.ts [hunk 2]
```diff
@@ -544,8 +544,37 @@ export class IgcSliderBaseComponent extends LitElement {
...
+        );
+      }
+    });
+  }
+
+  protected renderThumb(
+    value: number,
+    ariaLabel?: string,
+    thumbId?: string,
+    ariaValueText?: string
```
Comment (rkaraivanov) [inline src/components/slider/slider-base.ts:570]: A bit of nitpick but since all params are kind of internal to the component can you simplify the call signature to just the thumbId and get rest based on that?

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

File: src/components/slider/slider-base.ts (hunk 2 above)
Comment (onlyexeption) [reply src/components/slider/slider-base.ts:570]: I could, but how would you pass the aria label and the valueText like we do in `renderThumbs()` in range-slider.ts?

**Review by rkaraivanov — APPROVED** [review]
