### PR TITLE
fix(carousel): pause auto-rotation on pointer focus

### LINKED ISSUE #1731: Carousel resume animation behavior with focus
Okay, I get that's the current behavior replicating what the focus ring did, but it doesn't make sense. 
See https://igniteui.github.io/igniteui-webcomponents/?path=/story/carousel--inputs-template&args=interval:3000
Where focusing an input and moving the pointer away starts changing slides, which I don't think is nice and we should consider updating that behavior.

_Originally posted by @damyanpetev in https://github.com/IgniteUI/igniteui-webcomponents/pull/1684#discussion_r2129080103_

### PR DESCRIPTION
**Pull request by RivaIvanova**
Closes #1731

### CODE REVIEW

File: src/components/carousel/carousel.ts [hunk 1]
```diff
@@ -329,14 +327,13 @@ export default class IgcCarouselComponent extends EventEmitterMixin<
 
     addThemingController(this, all);
 
-    addSafeEventListener(this, 'pointerenter', this.handlePointerEnter);
-    addSafeEventListener(this, 'pointerleave', this.handlePointerLeave);
+    addSafeEventListener(this, 'pointerenter', this.handlePointerInteraction);
+    addSafeEventListener(this, 'pointerleave', this.handlePointerInteraction);
     addSafeEventListener(this, 'pointerdown', () => {
       this._hasInnerFocus = false;
     });
```
Comment (rkaraivanov) [inline src/components/carousel/carousel.ts]: This can be removed since pointerdown falls into the focusin handler logic.

File: src/components/carousel/carousel.ts [hunk 2]
```diff
@@ -389,42 +386,27 @@ export default class IgcCarouselComponent extends EventEmitterMixin<
...
 
-    if (this._hasInnerFocus) {
-      this._hasInnerFocus = false;
+    this._hasInnerFocus = event.type === 'focusin';
 
-      if (!this._hasMouseStop) {
-        this.handlePauseOnInteraction();
-      }
+    if (!this._hasPointerInteraction) {
+      this.handlePauseOnInteraction();
```
Comment (rkaraivanov) [inline src/components/carousel/carousel.ts:406]: Maybe something along the lines of:

```ts
private _handleFocusState(event: FocusEvent): void {
    const isFocusin = event.type === 'focusin';
    const hasFocusWithin = this.contains(document.activeElement);

    if (isFocusin && this._hasInnerFocus) {
      return;
    }

    this._hasInnerFocus = hasFocusWithin;
    if (!(this._hasPointerInteraction && this._hasInnerFocus)) {
      this.handlePauseOnInteraction();
    }
  }
```

**Review by rkaraivanov — CHANGES_REQUESTED** [review]
