### PR TITLE
fix(toast): adding alert role for toast

### LINKED ISSUE #479: Toast accessibility improvements
## Description  
The screen reader does not read the text inside the toast on opening.

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #479

### CODE REVIEW

File: src/components/toast/toast.ts [hunk 1]
```diff
@@ -36,6 +36,13 @@ export default class IgcToastComponent extends LitElement {
   @property({ type: Boolean, reflect: true, attribute: 'keep-open' })
   public keepOpen = false;
 
+  constructor() {
+    super();
+    if (!this.hasAttribute('role')) {
+      this.setAttribute('role', 'alert');
+    }
+  }
```
Comment (rkaraivanov) [inline src/components/toast/toast.ts:44]: You should move this to the connectedCallback hook.
As per the [specification](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

> The element must not gain any attributes or children, as this violates the expectations of consumers who use the [createElement](https://dom.spec.whatwg.org/#dom-document-createelement) or [createElementNS](https://dom.spec.whatwg.org/#dom-document-createelementns) methods.

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

**Comment by desig9stein** [comment]
@ChronosSF The reader on mac does not read anything with just the role, however, adding `aria-live="polite"` seems to fix the problem. 

We use the same approach in Angular.

[igx toast](https://www.infragistics.com/products/ignite-ui-angular/angular/components/toast#show-toast)
[aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live)

**Comment by ChronosSF** [comment]
Sadly, providing any aria-live seems to completely kill off the read out from Windows Narrator, but that seems to be the case with angular too. I guess having it read on Mac is better as we kinda go in the way of using nvda as baseline.

**Review by rkaraivanov — APPROVED** [review]
