### PR TITLE
fix(chips): update chip paddings to contain text padding

### LINKED ISSUE #17115: igx-chip has fixed font-size, which makes the content be really tight in smaller chip sizes
## Description  
The content gets squeezed because of large fonts when using chips with smaller chip sizes. 

 * igniteui-angular version: 21.1.x
 * browser: all

## Steps to reproduce  

1. Clone this repository https://github.com/kdinev/marketing-content-control-panel
2. `npm i && npm start`
3. Observe the chips on the landing page dashboard.

## Result  
Chip content has no breathing room

## Expected result  
There should be good spacing from the chip borders.

## Attachments  
Image

### PR DESCRIPTION
**Pull request by didimmova**
Related to https://github.com/IgniteUI/igniteui-angular/issues/17115

### CODE REVIEW

File: src/components/chip/chip.ts [hunk 1]
```diff
@@ -222,7 +222,7 @@ export default class IgcChipComponent extends EventEmitterMixin<
         @click=${this._handleSelect}
       >
         ${this._renderPrefix()}
-        <slot></slot>
```
Comment (kdinev) [inline src/components/chip/chip.ts:225]: Should there be a nested `<slot>` here?

Comment (didimmova) [reply src/components/chip/chip.ts:225]: If the slot is not nested, it's just plain text in the DOM and I cannot target the text to place the padding on it.

**Review by rkaraivanov — CHANGES_REQUESTED** [review]
Minor issue:
Since a new `content` part is introduced, it should be added to the JSDoc of the component `@csspart content - <description>`, update the relevant section of the specification and the documentation.

Otherwise, the template is fine.

**Comment by simeonoff** [comment]
> Minor issue: Since a new `content` part is introduced, it should be added to the JSDoc of the component `@csspart content - <description>`, update the relevant section of the specification and the documentation.
> 
> Otherwise, the template is fine.

Should be fixed now.

**Review by rkaraivanov — APPROVED** [review]
