### PR TITLE
fix(calendar): address ARIA violation when a week with all days hidden is rendered

### LINKED ISSUE #1636: [Bug] Calendar throws ARIA violations in certain configurations
### Which component(s) are affected?

Calendar

### Description

When `visibleMonths` is set to at least 2, for certain combinations of days-views, such as April+May, depending on the number of days, sometimes an empty "week" is rendered, where all days are _hidden_. This leads to a `Certain ARIA roles must contain particular children` violation.

Image

### Reproduction

1. Set visibleMonths to 2
2. Go to April 2025

### Workaround

In case all days in a week are hidden, the week should have `aria-hidden` set to `true`, or not be rendered at all?

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

5.3.0

### Browser/OS/Node environment

Chrome, Mozilla, etc.

### PR DESCRIPTION
**Pull request by ddaribo**
Closes #1636 

Note: An alternative approach might be to conditionally yield nothing in the `renderWeeks` generator if all days are hidden.

### CODE REVIEW

File: src/components/calendar/days-view/days-view.ts [hunk 1]
```diff
@@ -398,11 +398,10 @@ export default class IgcDaysViewComponent extends EventEmitterMixin<
     };
   }
 
-  protected renderDay(day: CalendarDay, today: CalendarDay) {
+  protected renderDay(day: CalendarDay, props: any) {
```
Comment (rkaraivanov) [inline src/components/calendar/days-view/days-view.ts:401]: I would prefer to not change the signature of this method.

File: src/components/calendar/days-view/days-view.ts [hunk 2]
```diff
@@ -481,12 +480,17 @@ export default class IgcDaysViewComponent extends EventEmitterMixin<
     const last = weeks.length - 1;
 
     for (const [idx, week] of weeks.entries()) {
+      const weekDaysProps: any[] = [];
+      for (const day of week) {
+        weekDaysProps.push(this.getDayProperties(day, today));
+      }
+      const hidden = weekDaysProps.every((p) => p.hidden);
```
Comment (rkaraivanov) [inline src/components/calendar/days-view/days-view.ts:487]: IMO it would be better to check just the first and the last week whether all the days are hidden before yielding the DOM pieces.

**Review by rkaraivanov — CHANGES_REQUESTED** [review]
Probably yielding nothing would be the better approach but that can be a separate refactoring task.

File: src/components/calendar/days-view/days-view.ts [hunk 3]
```diff
@@ -481,8 +482,14 @@ export default class IgcDaysViewComponent extends EventEmitterMixin<
...
     for (const [idx, week] of weeks.entries()) {
+      let hidden: boolean | undefined;
+      if (idx === 0 || idx === last) {
+        hidden =
+          week.every((day) => this.getDayProperties(day, today).hidden) ||
+          undefined;
+      }
       yield html`
-        <div role="row" part="days-row">
+        <div role="row" part="days-row" aria-hidden=${ifDefined(hidden)}>
```
Comment (rkaraivanov) [inline src/components/calendar/days-view/days-view.ts:492]: No point going the undefined route for the aria-hidden attribute.
Something along the lines of:
```ts
for (const [idx, week] of weeks.entries()) {
      let hidden = false;
      if (idx === 0 || idx === last) {
        hidden = week.every((day) => this.getDayProperties(day, today).hidden);
      }

      yield html`
        <div role="row" part="days-row" aria-hidden=${hidden}>
          ${this.showWeekNumbers
            ? this.renderWeekNumber(week[0], idx === last)
            : nothing}
          ${week.map((day) => this.renderDay(day, today))}
        </div>
      `;
    }
```

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

**Review by rkaraivanov — APPROVED** [review]
