### PR TITLE
fix(tabs): Nested tabs selection behavior

### LINKED ISSUE #713: An igc-tabs inside an igc-tab-panel (nested tab components) doesn't work well
## Description  

An `<igc-tabs>` inside an `<igc-tab-panel>` (nested tab components) doesn't work well.

## Steps to reproduce  

1. Put `<igc-tabs>` component inside another `<igc-tabs>` and its `<igc-tab-panel>` component, like the following code.

```html
<igc-tabs>
    <igc-tab panel="home">
        Home
    </igc-tab>
    ...
    <igc-tab-panel id="home">

        <igc-tabs>
          <igc-tab panel="P1">P1</igc-tab>
          ...
          <igc-tab-panel id="P1">
              Panel 1
          </igc-tab-panel>
          ...
        </igc-tabs>

    </igc-tab-panel>
    ...
```

3. Run it and click the tab in  the tab panel.

## Result  

The child tab contents disappeared.

movie-002

## Expected result  

An active tab and its contents should be switched correctly.

## Attachments  

You can reproduce this issue with the project attached below. (After downloading and extracting it, executing `npm i` and `npm start` will launch the app.)

[📦nested-igc-tabs.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/11058857/nested-igc-tabs.zip)

### PR DESCRIPTION
**Pull request by rkaraivanov**
Closes #713

### CODE REVIEW

File: src/components/tabs/tabs.ts [hunk 1]
```diff
@@ -121,17 +121,23 @@ export default class IgcTabsComponent extends EventEmitterMixin<
   private _mutationCallback({
     changes: { attributes, added, removed },
   }: MutationControllerParams<IgcTabComponent>) {
-    this.setSelectedTab(attributes.find((tab) => tab.selected));
+    const ownAttributes = attributes.filter(
+      (tab) => tab.closest(this.tagName) === this
+    );
+    const ownAdded = added.filter(({ target }) => target === this);
+    const ownRemoved = removed.filter(({ target }) => target === this);
```
Comment (damyanpetev) [inline src/components/tabs/tabs.ts:128]: Shouldn't we check these with `target.closest(this.tagName) === this` still? Just like the attributes. In most cases these should be direct `igc-tab` children, but technically those can be wrapped in containers, which will shift the target.

File: src/components/carousel/carousel.ts [hunk 2]
```diff
@@ -160,8 +160,9 @@ export default class IgcCarouselComponent extends EventEmitterMixin<
     if (activeSlides.length <= 1) {
       return;
     }
-
-    const idx = this.slides.indexOf(last(added.length ? added : attributes));
+    const idx = this.slides.indexOf(
+      added.length > 0 ? last(added).node : last(attributes)
```
Comment (damyanpetev) [inline src/components/carousel/carousel.ts:164]: Just a minor nit, but this being the same check as in the button group, can those be the same - i.e. `added.length ? ...`

**Review by damyanpetev — APPROVED** [review]
