### PR TITLE
fix(select): prefixes/suffixes and helper text not being rendered

### LINKED ISSUE #722: Select - Slots need additional render cycle to appear
## Description  
Prefix, Suffix & other slots in the Select are not rendered initially. They appear after you click on the element.

## Steps to reproduce  

1. Open [Codesandbox sample](https://codesandbox.io/s/mystifying-panini-ns04sh?file=/index.html)

## Result  
Prefix, Suffix & other slots' content is not visible. It becomes visible after clicking on the element.

## Expected result  
Content of the slots should be visible

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #722

### CODE REVIEW

File: src/components/select/select.ts [hunk 1]
```diff
@@ -252,6 +252,14 @@ export default class IgcSelectComponent extends EventEmitterMixin<
     super.firstUpdated();
     await this.updateComplete;
 
+    if (this.hasPrefixes || this.hasSuffixes) {
+      this.requestUpdate();
+    }
+
+    if (this.helperText) {
+      this.requestUpdate();
+    }
```
Comment (igdmdimitrov) [inline src/components/select/select.ts:261]:
```suggestion
    if (this.hasPrefixes || this.hasSuffixes || this.helperText) {
      this.requestUpdate();
    }
```

Comment (rkaraivanov) [reply src/components/select/select.ts:261]: Maybe attach a general `slotchange` handler to the slots which re-renders the component when there is slotted content?

**Review by rkaraivanov — APPROVED** [review]
