### PR TITLE
Swap tiles based on moving direction

### LINKED ISSUE #1607: [Bug]: Multiple tile swapping when dragging tiles with different sizes
### Which component(s) are affected?

Tile Manager

### Description

When dragging a small tile over a bigger one, the tiles change their positions multiple times rearranging the layout.

Image

### Reproduction

Steps to reproduce:
1. Run the Fin Dashboard sample from Storybook.
2. Slowly drag the tile from the top left to the right (over "Order Line Items" tile).
3. Observe that the tiles swap multiple times.

Actual behavior:
The tiles swap multiple times.

Expected result:
The tiles should swap only once.

### Workaround

Swapping tiles with similar size or moving the pointer faster does not trigger this behavior

### Is this a regression?

No

### Affected versions

Reproducible in 5.3.0

### Browser/OS/Node environment

N/A

### PR DESCRIPTION
**Pull request by mtsvyatkova**
Closes #1607

### CODE REVIEW

**Comment by mtsvyatkova** [comment]
This scenario is added in the Tile Manager specification for manual testing: https://github.com/IgniteUI/igniteui-webcomponents/wiki/Tile-Manager-Specification#manual

File: src/components/tile-manager/tile.ts [hunk 1]
```diff
@@ -402,14 +402,40 @@ export default class IgcTileComponent extends EventEmitterMixin<
...
+    if (this._previousPointerPosition) {
+      const deltaX = clientX - this._previousPointerPosition.x;
+      const deltaY = clientY - this._previousPointerPosition.y;
+
+      const movingRight = deltaX > 0;
+      const movingLeft = deltaX < 0;
+      const movingDown = deltaY > 0;
+      const movingUp = deltaY < 0;
+
+      const isHorizontalMove = Math.abs(deltaX) > Math.abs(deltaY);
```
Comment (gedinakova) [inline src/components/tile-manager/tile.ts:419]: It's very edgy, but if they are equal?

File: src/components/tile-manager/tile.ts [hunk 2]
```diff
@@ -402,14 +402,40 @@ export default class IgcTileComponent extends EventEmitterMixin<
...
+      const isVerticalMove = Math.abs(deltaY) > Math.abs(deltaX);
```
Comment (rkaraivanov) [inline src/components/tile-manager/tile.ts:420]: I think we should abstract this state into the drag controller itself. It can hold the previous pointer coordinates when a drag is initiated and return the _direction_ while dragging in its callback parameters. At least it will simplify the code inside the tile drag handler.

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

File: src/components/common/controllers/drag.ts [hunk 3]
```diff
@@ -6,14 +6,20 @@ import type {
...
+  roundByDPR,
+} from '../util.js';
 
 type DragCallback = (parameters: DragCallbackParameters) => unknown;
 type DragCancelCallback = (state: DragState) => unknown;
 
 export type DragCallbackParameters = {
   event: PointerEvent;
   state: DragState;
+  direction: Direction | null;
```
Comment (rkaraivanov) [inline src/components/common/controllers/drag.ts:22]: IMO this should be a property of the `DragState` object

File: src/components/common/controllers/drag.ts [hunk 4]
```diff
@@ -249,7 +287,15 @@ class DragController implements ReactiveController {
     this._createDragGhost();
     this._updatePosition(event);
 
-    const parameters = { event, state: this._stateParameters };
+    this._previousPointerPosition = { x: event.clientX, y: event.clientY };
+    this._direction = this._trackPointerMovement(event.clientX, event.clientY);
```
Comment (rkaraivanov) [inline src/components/common/controllers/drag.ts:291]: I think the direction should be computed in the pointermove handler

File: src/components/common/controllers/drag.ts [hunk 5]
```diff
@@ -28,6 +34,13 @@ type DragState = State & {
   element: Element | null;
 };
 
+type Direction = {
+  isHorizontalMove: boolean;
+  movingDown: boolean;
+  movingToEndHorizontally: boolean;
+  movingToStartHorizontally: boolean;
+};
```
Comment (rkaraivanov) [inline src/components/common/controllers/drag.ts:42]: Can this be a union type? Something along the lines of `left` | `top` | 'top-left`?

File: src/components/common/controllers/drag.ts [hunk 6]
```diff
@@ -267,16 +313,30 @@ class DragController implements ReactiveController {
...
     this._updateMatcher(event);
 
-    const parameters = { event, state: this._stateParameters };
+    this._direction = this._trackPointerMovement(event.clientX, event.clientY);
+
+    const parameters = {
+      event,
+      state: this._stateParameters,
+      direction: this._direction,
+    };
```
Comment (rkaraivanov) [inline src/components/common/controllers/drag.ts:322]: If `direction` is a property of the `DragState` you can shove those calculations in the `_stateParameters` getter and only update the previous pointer coordinates here

File: src/components/common/controllers/drag.ts [hunk 7]
```diff
@@ -267,16 +313,30 @@ class DragController implements ReactiveController {
...
+
     this._options.move?.call(this._host, parameters);
 
     this._assignPosition(this._dragItem);
   }
 
   private _handlePointerEnd(event: PointerEvent): void {
+    this._previousPointerPosition = null;
```
Comment (rkaraivanov) [inline src/components/common/controllers/drag.ts:330]: Maybe just initialize the previous coordinates as `{x: 0, y: 0}` on initialization of the controller and then just updated through the pointerdown -> pointermove cycle?

File: src/components/common/controllers/drag.ts [hunk 8]
```diff
@@ -109,6 +122,8 @@ class DragController implements ReactiveController {
   private _hasPointerCapture = false;
 
   private _ghost: HTMLElement | null = null;
+  private _previousPointerPosition: { x: number; y: number } | null = null;
+  private _direction: Direction | null = null;
```
Comment (rkaraivanov) [inline src/components/common/controllers/drag.ts:126]: Won't need it if it's a part of the `DragState` object

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

**Review by rkaraivanov — APPROVED** [review]
