### PR TITLE
fix(dropdown): Dispose of top-level event listeners

### LINKED ISSUE #462: Toggle controller does not dispose of top-level listeners
## Steps to reproduce  

1. Open a dropdown component.
2. Click outside of the dropdown area.
3. Continue clicking outside the component after it is closed.

## Result  
Event listeners are attached and continue to fire off events.

## Expected result  
Event listeners should be disposed, and no events should fire.

## Attachments  

https://user-images.githubusercontent.com/20106115/181744576-f1becbed-0c9a-45f9-ae20-f5ee18445386.mp4

### PR DESCRIPTION
**Pull request by rkaraivanov**
Closes #462

### CODE REVIEW

**Review by simeonoff — DISMISSED** [review]

File: src/components/toggle/toggle.controller.ts [hunk 1]
```diff
@@ -28,6 +28,18 @@ export class IgcToggleController implements ReactiveController {
   private initialScrollLeft = 0;
   private _target!: HTMLElement;
   private _hide?: Function;
+  private _abortController = new AbortController();
```
Comment (damyanpetev) [inline src/components/toggle/toggle.controller.ts:31]: Hello new $destroy subject :D

File: src/components/toggle/toggle.controller.ts [hunk 2]
```diff
@@ -57,35 +69,36 @@ export class IgcToggleController implements ReactiveController {
...
+      document.addEventListener('click', this.documentClicked, options);
     }
+
+    document.addEventListener('scroll', this.handleScroll, options);
   }
 
-  private removeEventListeners() {
-    document.removeEventListener('click', this.documentClicked, true);
-    document.removeEventListener('scroll', this.handleScroll, true);
+  private addListeners() {
```
Comment (damyanpetev) [inline src/components/toggle/toggle.controller.ts:98]: Minor nit: Kind of weird this being called `addListeners` when it both adds and removes them now.

**Review by simeonoff — APPROVED** [review]

**Review by damyanpetev — APPROVED** [review]
